:ruby_version: 'ruby-1.9.3-p545'
:bundler_version: 1.7.12
:test_pattern:
  - features/*.feature
  - spec/**_spec.rb
#plan:
#  - default
#profiles:
#  default:
#    script: "/home/ubuntu/foo.sh"
#    #tests:
#    #  - '/home/ubuntu/foo.sh'
#    #  - '/home/ubuntu/bar.sh'
#    environment:
#      'FOOBARVAR': 'foobarval'
#      'PATH2': '/home/ubuntu/tmp'
#    timeout: 120
