plan:
  - default
profiles:
  default:
    script: "/home/ubuntu/foo.sh"
    #tests:
    #  - '/home/ubuntu/foo.sh'
    #  - '/home/ubuntu/bar.sh'
    environment:
      'FOOBARVAR': 'foobarval'
      'PATH2': '/home/ubuntu/tmp'
    timeout: 60
